services:
    postgresql:
        image: postgres:latest
        ports:
            - 5432:5432
        tty: true
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test

    redis:
        image: redis:latest
        ports:
            - 6379:6379
        tty: true
        